"""empty message

Revision ID: 227777ff6e80
Revises: 729cefd0b594
Create Date: 2021-11-22 20:00:11.486105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227777ff6e80'
down_revision = '729cefd0b594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_name', table_name='node')
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.create_index('ix_node_name', 'node', ['name'], unique=1)
    # ### end Alembic commands ###
