"""empty message

Revision ID: 77549e10d129
Revises: 83e2d56a1b87
Create Date: 2020-11-28 19:46:44.988436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77549e10d129'
down_revision = '83e2d56a1b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_column('node', 'name')
    # ### end Alembic commands ###
